export const CONSULTAR_PROJETOS = "CONSULTAR_PROJETOS";
export const ADICIONAR_PROJETO = "ADICIONAR_PROJETO";
export const ALTERAR_PROJETO = "ALTERAR_PROJETO";
export const REMOVER_PROJETO = "REMOVER_PROJETO";
