export const ADICIONA_PROJETO = "ADICIONA_PROJETO";
export const EDITA_PROJETO = "EDITA_PROJETO";
export const EXCLUIR_PROJETO = "EXCLUIR_PROJETO";
export const BUSCA_PROJETOS = "BUSCA_PROJETOS";

export const BUSCA_TAREFAS = "BUSCA_TAREFAS";
export const ADICIONA_TAREFAS = "ADICIONA_TAREFAS";
export const EDITA_TAREFAS = "EDITA_TAREFAS";
