export const CONSULTAR_PROJETOS = "CONSULTAR_PROJETOS";
export const ADICIONAR_PROJETO = "ADICIONAR_PROJETO";
export const ALTERAR_PROJETO = "ALTERAR_PROJETO";
export const REMOVER_PROJETO = "REMOVER_PROJETO";

export const OBTER_TAREFAS = "OBTER_TAREFAS";
export const ADICIONAR_TAREFAS = "ADICIONAR_TAREFAS";
export const ALTERAR_TAREFAS = "ALTERAR_TAREFAS";
